### ISSUE TITLE
Problem installing package on Mac Catalina/R 4.0.1 

### ISSUE THREAD

**Issue by sumtxt** [goulart-paul/osqp-r#20] opened 2020-08-01 20:56 UTC
I am getting error messages when trying to install the package. Any ideas what the problem is?  R sessionInfo() output is also below.

```
install.packages("osqp")
Installing package into '/usr/local/lib/R/4.0/site-library'
(as 'lib' is unspecified)

trying URL 'https://cran.rstudio.com/src/contrib/osqp_0.6.0.3.tar.gz'
Content type 'application/x-gzip' length 975221 bytes (952 KB)
==================================================
downloaded 952 KB

* installing *source* package ‘osqp’ ...
** package ‘osqp’ successfully unpacked and MD5 sums checked
** using staged installation
+++ command -v cmake
++ '[' -x /usr/local/bin/cmake ']'
++ echo '-- Trying to build libosqp.a via cmake ...'
-- Trying to build libosqp.a via cmake ...
++ cd src/osqp_sources
++ mkdir -p build
++ cd build
++ cmake -DR_LANG=TRUE -DCMAKE_INSTALL_PREFIX:PATH=../../ ..
-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- We are on a Darwin system
-- Embedded is OFF
-- Printing is ON
-- Profiling is ON
-- User interrupt is ON
-- Floats are OFF
-- Long integers (64bit) are ON
-- Code coverage is OFF
-- MKL Pardiso: ON
-- We are building the R interface
-- R exec is: /usr/local/bin/R
-- R root dir is: /usr/local/Cellar/r/4.0.1/lib/R
-- R includes are in: /usr/local/include
-- Floats are OFF
-- Long integers (64bit) are ON
-- Configuring done
-- Generating done
-- Build files have been written to: /private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/build
++ cmake --build . --target install
Scanning dependencies of target qdldlobject
[  2%] Building C object lin_sys/direct/qdldl/qdldl_sources/CMakeFiles/qdldlobject.dir/src/qdldl.c.o
[  2%] Built target qdldlobject
Scanning dependencies of target linsys_pardiso
[  5%] Building C object lin_sys/direct/CMakeFiles/linsys_pardiso.dir/pardiso/pardiso_interface.c.o
[  8%] Building C object lin_sys/direct/CMakeFiles/linsys_pardiso.dir/pardiso/pardiso_loader.c.o
[  8%] Built target linsys_pardiso
Scanning dependencies of target linsys_qdldl
[ 11%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_1.c.o
[ 13%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_2.c.o
[ 16%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_aat.c.o
[ 19%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_control.c.o
[ 22%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_defaults.c.o
[ 25%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_info.c.o
[ 27%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_order.c.o
[ 30%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_post_tree.c.o
[ 33%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_postorder.c.o
[ 36%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_preprocess.c.o
[ 38%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_valid.c.o
[ 41%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/SuiteSparse_config.c.o
[ 44%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/qdldl_interface.c.o
[ 44%] Built target linsys_qdldl
Scanning dependencies of target osqpstatic
[ 47%] Building C object CMakeFiles/osqpstatic.dir/src/auxil.c.o
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/auxil.c:214:3: warning: implicit declaration of function 'project' is invalid in C99 [-Wimplicit-function-declaration]
  project(work, work->z);
  ^
1 warning generated.
[ 50%] Building C object CMakeFiles/osqpstatic.dir/src/error.c.o
[ 52%] Building C object CMakeFiles/osqpstatic.dir/src/lin_alg.c.o
[ 55%] Building C object CMakeFiles/osqpstatic.dir/src/osqp.c.o
[ 58%] Building C object CMakeFiles/osqpstatic.dir/src/proj.c.o
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:4:14: error: unknown type name 'OSQPWorkspace'
void project(OSQPWorkspace *work, c_float *z) {
             ^
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:4:35: error: unknown type name 'c_float'; did you mean 'float'?
void project(OSQPWorkspace *work, c_float *z) {
                                  ^~~~~~~
                                  float
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:5:3: error: use of undeclared identifier 'c_int'
  c_int i, m;
  ^
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:7:3: error: use of undeclared identifier 'm'
  m = work->data->m;
  ^
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:9:8: error: use of undeclared identifier 'i'
  for (i = 0; i < m; i++) {
       ^
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:9:15: error: use of undeclared identifier 'i'
  for (i = 0; i < m; i++) {
              ^
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:9:19: error: use of undeclared identifier 'm'
  for (i = 0; i < m; i++) {
                  ^
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:9:22: error: use of undeclared identifier 'i'
  for (i = 0; i < m; i++) {
                     ^
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:10:7: error: use of undeclared identifier 'i'
    z[i] = c_min(c_max(z[i],
      ^
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:10:12: warning: implicit declaration of function 'c_min' is invalid in C99 [-Wimplicit-function-declaration]
    z[i] = c_min(c_max(z[i],
           ^
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:10:18: warning: implicit declaration of function 'c_max' is invalid in C99 [-Wimplicit-function-declaration]
    z[i] = c_min(c_max(z[i],
                 ^
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:10:26: error: use of undeclared identifier 'i'
    z[i] = c_min(c_max(z[i],
                         ^
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:11:38: error: use of undeclared identifier 'i'
                       work->data->l[i]), // Between lower
                                     ^
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:12:32: error: use of undeclared identifier 'i'
                 work->data->u[i]);       // and upper bounds
                               ^
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:16:25: error: unknown type name 'OSQPWorkspace'
void project_normalcone(OSQPWorkspace *work, c_float *z, c_float *y) {
                        ^
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:16:46: error: unknown type name 'c_float'; did you mean 'float'?
void project_normalcone(OSQPWorkspace *work, c_float *z, c_float *y) {
                                             ^~~~~~~
                                             float
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:16:58: error: unknown type name 'c_float'; did you mean 'float'?
void project_normalcone(OSQPWorkspace *work, c_float *z, c_float *y) {
                                                         ^~~~~~~
                                                         float
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:17:3: error: use of undeclared identifier 'c_int'
  c_int i, m;
  ^
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:21:3: error: use of undeclared identifier 'm'
  m = work->data->m;
  ^
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:23:8: error: use of undeclared identifier 'i'
  for (i = 0; i < m; i++) {
       ^
/private/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T/RtmpcHq2W5/R.INSTALL8cdf3b51abb4/osqp/src/osqp_sources/src/proj.c:23:15: error: use of undeclared identifier 'i'
  for (i = 0; i < m; i++) {
              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
make[2]: *** [CMakeFiles/osqpstatic.dir/src/proj.c.o] Error 1
make[1]: *** [CMakeFiles/osqpstatic.dir/all] Error 2
make: *** [all] Error 2
ERROR: configuration failed for package ‘osqp’
* removing ‘/usr/local/lib/R/4.0/site-library/osqp’
```

```
sessionInfo()
R version 4.0.1 (2020-06-06)
Platform: x86_64-apple-darwin19.5.0 (64-bit)
Running under: macOS Catalina 10.15.5

Matrix products: default
BLAS/LAPACK: /usr/local/Cellar/openblas/0.3.9/lib/libopenblasp-r0.3.9.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] colorout_1.2-2

loaded via a namespace (and not attached):
 [1] gert_0.3         memuse_4.1-0     clisymbols_1.2.0 prompt_1.0.0    
 [5] digest_0.6.25    crayon_1.3.4     prettycode_1.1.0 sys_3.4         
 [9] credentials_1.1  rprofile_0.1.3   rlang_0.4.7      remotes_1.1.0   
[13] tools_4.0.1      compiler_4.0.1   parallel_4.0.1   askpass_1.1     
[17] memoise_1.1.0    openssl_1.4.2   
```

**Comment by goulart-paul** [comment] 2020-08-03 16:54
I can't reproduce it, but it seems like the problem is that some or all type definitions are missing when trying to compile the osqp main static library. 

This doesn't really solve the problem, but you might try either :

1) Downloading the compiled binaries directly from CRAN [here](https://cran.r-project.org/web/packages/osqp/index.html).
2) Try compiling directly by pulling source from github.  Instructions [here](https://osqp.org/docs/installation/r.html#from-sources).

**Comment by sumtxt** [comment] 2020-08-03 18:03
`install.packages("osqp", type='mac.binary')` works for me. But compiling from source (either within R or outside does not). Relatedly, there seems to be a problem with the Github repo: 

```
> remotes::install_git("git://github.com/OxfordControl/osqp-r",submodules = TRUE)
Downloading git repo git://github.com/OxfordControl/osqp-r
'/usr/local/bin/git' clone --depth 1 --no-hardlinks --recurse-submodules --branch R-interface-dev git://github.com/OxfordControl/osqp /var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T//RtmpJVE1K3/filedc302c627317/src/osqp_sources
Cloning into '/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T//RtmpJVE1K3/filedc302c627317/src/osqp_sources'...
warning: Could not find remote branch R-interface-dev to clone.
fatal: Remote branch R-interface-dev not found in upstream origin
Error: Failed to install 'unknown package' from Git:
  Command failed (128)
In addition: Warning messages:
1: In readLines(file) :
  incomplete final line found on '/var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T//RtmpJVE1K3/filedc302c627317/.gitmodules'
2: In system(full, intern = TRUE, ignore.stderr = quiet) :
  running command ''/usr/local/bin/git' clone --depth 1 --no-hardlinks --recurse-submodules --branch R-interface-dev git://github.com/OxfordControl/osqp /var/folders/t1/9nfnfvn95f99vzc_r1p5gs1h0000gq/T//RtmpJVE1K3/filedc302c627317/src/osqp_sources' had status 128
```

**Comment by goulart-paul** [comment] 2020-08-03 18:11
Thanks.   I will have a look, but for now I am glad that the binaries worked at least.

I suspect it is something to do with the `--branch R-interface-dev` part of the git clone command.   I don't understand why that's there.

**Comment by goulart-paul** [comment] 2020-08-08 22:37
I think it might not be the same issue, but I was not able to build OSQP for R on OSX either, having previously done so without an issue.   I believe that the issue in my case was clang related.   I solved my issue be just doing `xcode-select --install`.

Does either that, or updating your xcode install, fix the issue for you?   If not, does the [osqp basic install ](https://osqp.org/docs/get_started/sources.html)build for you?

**Comment by sumtxt** [comment] 2020-08-09 06:26
I can compile the osqp library without problems ("osqp basic install"). See output below. This is my clang version (current version that comes with xcode):

```
Apple clang version 11.0.3 (clang-1103.0.32.29)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```
➜  build git:(master) cmake --build .

Scanning dependencies of target qdldlobject
[  1%] Building C object lin_sys/direct/qdldl/qdldl_sources/CMakeFiles/qdldlobject.dir/src/qdldl.c.o
[  1%] Built target qdldlobject
Scanning dependencies of target linsys_pardiso
[  3%] Building C object lin_sys/direct/CMakeFiles/linsys_pardiso.dir/pardiso/pardiso_interface.c.o
[  5%] Building C object lin_sys/direct/CMakeFiles/linsys_pardiso.dir/pardiso/pardiso_loader.c.o
[  5%] Built target linsys_pardiso
Scanning dependencies of target linsys_qdldl
[  7%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_1.c.o
[  9%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_2.c.o
[ 11%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_aat.c.o
[ 13%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_control.c.o
[ 15%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_defaults.c.o
[ 17%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_info.c.o
[ 19%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_order.c.o
[ 21%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_post_tree.c.o
[ 23%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_postorder.c.o
[ 25%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_preprocess.c.o
[ 26%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_valid.c.o
[ 28%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/SuiteSparse_config.c.o
[ 30%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/qdldl_interface.c.o
[ 30%] Built target linsys_qdldl
Scanning dependencies of target osqpstatic
[ 32%] Building C object CMakeFiles/osqpstatic.dir/src/auxil.c.o
[ 34%] Building C object CMakeFiles/osqpstatic.dir/src/error.c.o
[ 36%] Building C object CMakeFiles/osqpstatic.dir/src/lin_alg.c.o
[ 38%] Building C object CMakeFiles/osqpstatic.dir/src/osqp.c.o
[ 40%] Building C object CMakeFiles/osqpstatic.dir/src/proj.c.o
[ 42%] Building C object CMakeFiles/osqpstatic.dir/src/scaling.c.o
[ 44%] Building C object CMakeFiles/osqpstatic.dir/src/util.c.o
[ 46%] Building C object CMakeFiles/osqpstatic.dir/src/kkt.c.o
[ 48%] Building C object CMakeFiles/osqpstatic.dir/src/cs.c.o
[ 50%] Building C object CMakeFiles/osqpstatic.dir/src/polish.c.o
[ 51%] Building C object CMakeFiles/osqpstatic.dir/src/lin_sys.c.o
[ 53%] Building C object CMakeFiles/osqpstatic.dir/src/ctrlc.c.o
[ 55%] Building C object CMakeFiles/osqpstatic.dir/lin_sys/lib_handler.c.o
[ 57%] Linking C static library out/libosqp.a
[ 57%] Built target osqpstatic
Scanning dependencies of target osqp_demo
[ 59%] Building C object CMakeFiles/osqp_demo.dir/examples/osqp_demo.c.o
[ 61%] Linking C executable out/osqp_demo
[ 61%] Built target osqp_demo
Scanning dependencies of target osqp
[ 63%] Building C object CMakeFiles/osqp.dir/src/auxil.c.o
[ 65%] Building C object CMakeFiles/osqp.dir/src/error.c.o
[ 67%] Building C object CMakeFiles/osqp.dir/src/lin_alg.c.o
[ 69%] Building C object CMakeFiles/osqp.dir/src/osqp.c.o
[ 71%] Building C object CMakeFiles/osqp.dir/src/proj.c.o
[ 73%] Building C object CMakeFiles/osqp.dir/src/scaling.c.o
[ 75%] Building C object CMakeFiles/osqp.dir/src/util.c.o
[ 76%] Building C object CMakeFiles/osqp.dir/src/kkt.c.o
[ 78%] Building C object CMakeFiles/osqp.dir/src/cs.c.o
[ 80%] Building C object CMakeFiles/osqp.dir/src/polish.c.o
[ 82%] Building C object CMakeFiles/osqp.dir/src/lin_sys.c.o
[ 84%] Building C object CMakeFiles/osqp.dir/src/ctrlc.c.o
[ 86%] Building C object CMakeFiles/osqp.dir/lin_sys/lib_handler.c.o
[ 88%] Linking C shared library out/libosqp.dylib
[ 88%] Built target osqp
Scanning dependencies of target qdldl
[ 90%] Building C object lin_sys/direct/qdldl/qdldl_sources/CMakeFiles/qdldl.dir/src/qdldl.c.o
[ 92%] Linking C shared library out/libqdldl.dylib
[ 92%] Built target qdldl
Scanning dependencies of target qdldlstatic
[ 94%] Building C object lin_sys/direct/qdldl/qdldl_sources/CMakeFiles/qdldlstatic.dir/src/qdldl.c.o
[ 96%] Linking C static library out/libqdldl.a
[ 96%] Built target qdldlstatic
Scanning dependencies of target qdldl_example
[ 98%] Building C object lin_sys/direct/qdldl/qdldl_sources/CMakeFiles/qdldl_example.dir/examples/example.c.o
[100%] Linking C executable out/qdldl_example
[100%] Built target qdldl_example
```

**Comment by goulart-paul** [comment] 2020-08-09 14:49
Thanks.   I have tried to reproduce the error, but I get a successful build in both R 3.6.1 and R 4.0.2.   This worked for both clang version 10.0.1 and version 11.0.3, and using both `R CMD install` and from within R using `install.packages("osqp")`.

However, I was getting (different) build errors in clang 10.0.1 and prior to doing `xcode-select --install .`.   This seemed to relate to an inability of clang to find some system headers (see [here](https://stackoverflow.com/questions/51761599/cannot-find-stdio-h)) when compiling from source for R, although I was still able to do a basic OSQP build.   

That doesn't appear to be your problem though, since it looks like osqp just isn't including its own headers properly, or can't find them.    

All of your osqp source files appear to be in `/private/var/folders/...../osqp/src/osqp_sources/src`.   What's in `/private/var/folders/...../osqp/src/osqp_sources/include`?

**Comment by sumtxt** [comment] 2020-08-09 18:28
This is the file list for the folder `/private/var/folders/.../osqp/src/osqp_sources/include`

```
proj.h
kkt.h
util.h
osqp.h
polish.h
scaling.h
lin_sys.h
error.h
lin_alg.h
cs.h
ctrlc.h
constants.h
auxil.h
CMakeLists.txt
types.h
glob_opts.h
osqp_configure.h
```

**Comment by goulart-paul** [comment] 2020-08-09 21:47
I confirmed the error you mentioned with installing via `remotes::install_git("git://github.com/OxfordControl/osqp-r",submodules = TRUE)`.  It appears to be fixed now following the merge of PR #21, which removes a dodgy branch specification in the `.gitmodules` file.

The other errors you saw (i.e. using an `R CMD install .` type installation) might be unrelated.   If you still get errors along the lines of your original issue description, you could modify the first `cmake`command  in the R package `configure` file to :
`cmake -DR_LANG=TRUE -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=../../ ..` 
before running the install.   That should force cmake to give verbose output during its build of the OSQP static library, which might clarify the problem.

**Comment by sumtxt** [comment] 2020-08-10 07:13
I can confirm that `remotes::install_git("git://github.com/OxfordControl/osqp-r",submodules = TRUE)` now works. The other error still occurs. The relevant part of the verbose output is below ("[username]" is a placeholder):

```
[ 58%] Building C object CMakeFiles/osqpstatic.dir/src/proj.c.o
/Library/Developer/CommandLineTools/usr/bin/cc -DR_LANG -I/usr/local/include -I/Users/[username]/Working/osqp-r/src/osqp_sources/lin_sys/direct/qdldl -I/Users/[username]/Working/osqp-r/src/osqp_sources/lin_sys/direct/qdldl/qdldl_sources/include -I/Users/[username]/Working/osqp-r/src/osqp_sources/lin_sys/direct/pardiso -I/Users/[username]/Working/osqp-r/src/osqp_sources/include  -O3 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC   -o CMakeFiles/osqpstatic.dir/src/proj.c.o   -c /Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:4:14: error: unknown type name 'OSQPWorkspace'
void project(OSQPWorkspace *work, c_float *z) {
             ^
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:4:35: error: unknown type name 'c_float'; did you mean 'float'?
void project(OSQPWorkspace *work, c_float *z) {
                                  ^~~~~~~
                                  float
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:5:3: error: use of undeclared identifier 'c_int'
  c_int i, m;
  ^
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:7:3: error: use of undeclared identifier 'm'
  m = work->data->m;
  ^
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:9:8: error: use of undeclared identifier 'i'
  for (i = 0; i < m; i++) {
       ^
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:9:15: error: use of undeclared identifier 'i'
  for (i = 0; i < m; i++) {
              ^
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:9:19: error: use of undeclared identifier 'm'
  for (i = 0; i < m; i++) {
                  ^
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:9:22: error: use of undeclared identifier 'i'
  for (i = 0; i < m; i++) {
                     ^
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:10:7: error: use of undeclared identifier 'i'
    z[i] = c_min(c_max(z[i],
      ^
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:10:12: warning: implicit declaration of function 'c_min' is invalid
      in C99 [-Wimplicit-function-declaration]
    z[i] = c_min(c_max(z[i],
           ^
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:10:18: warning: implicit declaration of function 'c_max' is invalid
      in C99 [-Wimplicit-function-declaration]
    z[i] = c_min(c_max(z[i],
                 ^
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:10:26: error: use of undeclared identifier 'i'
    z[i] = c_min(c_max(z[i],
                         ^
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:11:38: error: use of undeclared identifier 'i'
                       work->data->l[i]), // Between lower
                                     ^
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:12:32: error: use of undeclared identifier 'i'
                 work->data->u[i]);       // and upper bounds
                               ^
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:16:25: error: unknown type name 'OSQPWorkspace'
void project_normalcone(OSQPWorkspace *work, c_float *z, c_float *y) {
                        ^
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:16:46: error: unknown type name 'c_float'; did you mean 'float'?
void project_normalcone(OSQPWorkspace *work, c_float *z, c_float *y) {
                                             ^~~~~~~
                                             float
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:16:58: error: unknown type name 'c_float'; did you mean 'float'?
void project_normalcone(OSQPWorkspace *work, c_float *z, c_float *y) {
                                                         ^~~~~~~
                                                         float
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:17:3: error: use of undeclared identifier 'c_int'
  c_int i, m;
  ^
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:21:3: error: use of undeclared identifier 'm'
  m = work->data->m;
  ^
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:23:8: error: use of undeclared identifier 'i'
  for (i = 0; i < m; i++) {
       ^
/Users/[username]/Working/osqp-r/src/osqp_sources/src/proj.c:23:15: error: use of undeclared identifier 'i'
  for (i = 0; i < m; i++) {
              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
make[2]: *** [CMakeFiles/osqpstatic.dir/src/proj.c.o] Error 1
make[1]: *** [CMakeFiles/osqpstatic.dir/all] Error 2
```

**Comment by goulart-paul** [comment] 2021-03-18 15:42
I realise that this issue is not quite old, but I have just seen a similar problem (not identical) caused by a clash with an installation of SuiteSparse somewhere else on my machine.   The root cause in my case was an installation of octave via homebrew, which put all of the SuiteSparse headers in `/usr/local/include`.

**Closed as completed** 2021-12-02 12:44 UTC
